version: '3.1'

services:
  db: 
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - '.:/app'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: todo_dev
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres

volumes:
  pgdata: